name: looker tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    python-version: 3.7

    steps:
    - uses: actions/checkout@v1
    - name: Set environment variables
      env:
        LOOKERSDK_API_VERSION: ${{ LOOKERSDK_API_VERSION }}
        LOOKERSDK_BASE_URL: ${{ LOOKERSDK_BASE_URL }}
        LOOKERSDK_CLIENT_ID: ${{ LOOKERSDK_CLIENT_ID }}
        LOOKERSDK_CLIENT_SECRET: ${{ LOOKERSDK_CLIENT_SECRET }}
        LOOKERSDK_TIMEOUT: ${{ LOOKERSDK_TIMEOUT }}
        LOOKERSDK_VERIFY_SSL: ${{ LOOKERSDK_VERIFY_SSL }}

    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/actions/requirements.txt
    - name: Run test
      run: |
        python .github/actions/run_tests.py ${{ github.head_ref }}
